name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create virtual environment and install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install .

    - name: Test with pytest and generate coverage report
      run: |
        source venv/bin/activate
        pip install pytest pytest-cov
        python -m pytest -m "not pyvista" --cov=./ --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

        

# name: Tests on PR

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#   workflow_dispatch:

# jobs:
#   validate:
#     defaults:
#       run:
#         shell: bash -l {0}

#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out
#         uses: actions/checkout@v4

#       - name: Initialize miniconda
#         uses: conda-incubator/setup-miniconda@v3
#         with:
#           activate-environment: test
#           auto-update-conda: true
#           environment-file: environment.yml
#           auto-activate-base: false
#           python-version: 3.12

#       - name: Conda config
#         run: >-
#           conda config --set always_yes yes
#           --set changeps1 no

#       - name: Install requirements
#         run: |
#           conda install --file requirements/conda.txt
#           conda install --file requirements/test.txt
#           python -m pip install . --no-deps

#       - name: Validate
#         run: |
#           python -m pytest

#       - name: Comment Codecov coverage reports 
#         uses: codecov/codecov-action@v4.0.1
#         with:
#           token: ${{ secrets.CODECOV_TOKEN }}
# # jobs:
# #   validate:
# #     uses: bobleesj/release-scripts/.github/workflows/_tests-on-pr.yml@v0
# #     with:
# #       project: bobleesj.release
# #       c_extension: false
# #       headless: false
# #     secrets:
# #       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}